# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
siena: &siena
  adapter: postgresql
  host: localhost
  username: dbuser
  password: dbpass

development:
  <<: *siena
  database: dbname

#test:
#  <<: *siena
#  database: dbname


